logging:
  level:
    root: INFO

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always

endpoints:
  health:
    sensitive: false


clientId: "pcVqhKoClIDBscwO1lWanGF0wvjBgyX2"
clientSecret: "l8aGW9zA7DNGkhBS"