logging:
  level:
    root: INFO

management:
  health:
    diskspace:
      enabled: false
  endpoint:
    health:
      show-details: always

greeting: ${sm://greeting}



clientId: "pcVqhKoClIDBscwO1lWanGF0wvjBgyX2"
clientSecret: "l8aGW9zA7DNGkhBS"